### PR TITLE
Added setting to move the close, maximize, and minimize to the left for better linux/OS X integration

### PR DESCRIPTION
**Pull request by Boltgolt**
Note: saveSettings in app/assets/js/app/settings.js is not saving the added setting. I couldn't find where saveSettings was pointing to, perhaps it's java?

### CODE REVIEW

**Comment by Codeusa** [comment]
Settings are handled on the java side of things, I will invertedNav to the core code.

**Comment by Codeusa** [comment]
Hi @Boltgolt the setting was added but after testing it seems it doesn't actually inverse your nav bar, even when executing the JS directly. 

That being said it will be in the next release in the settings as 

```
"invertedNav":true

```

Please double check to make sure you didn't miss anything.

**Comment by Boltgolt** [comment]
Oops, didn't add the css file. I'll create a second pull request when I'm home

**Comment by Codeusa** [comment]
@Boltgolt keep in mind we utilize scss so you'll need to append it there, compile it into css.

**Pull request merged**
