### PR TITLE
Fix CORS when use "createMediaElementSource" and minor changes

### PR DESCRIPTION
**Pull request by danilobrinu**
Fix CORS when use "createMediaElementSource", support browser-sync, fomat coding, etc.

### CODE REVIEW

**Comment by Codeusa** [comment]
During automatic pull testing, audio data failed to play from disk, please look into this.

**Comment by danilobrinu** [comment]
Thx i see, right now

**Comment by danilobrinu** [comment]
@Codeusa u run npm install again ?? ... i added browser-sync in this pull

**Comment by danilobrinu** [comment]
How to test play audio form disk ?

**Pull request merged**
