### PR TITLE
Scroll down loading for user collection and Volume operations.

### PR DESCRIPTION
**Pull request by srcnalt**
appendLocalCollection method now loads first n items to fill the screen.

appendLocalCollectionScroll method is called if viewport is scrolled down and loads the next n item if screen is to hit bottom of viewport.

songCollection.itemCount is number of items to fill the screen. This var is changed if screen height changes.

Volume icon changes over volume level change. Clicking on volume icon mutes the sound.

### CODE REVIEW

**Comment by Codeusa** [comment]
This indeed fixed the collection lag issue, let me know how you want to receive your bounty

**Comment by srcnalt** [comment]
That'd be great for a NEET like me actually :smile:

**Comment by srcnalt** [comment]
@Codeusa, #45 is merged over the volume ops code here but it has some programming issues eehehe, pic related.

And my paypal is sercan.altundas@gmail.com forgot to add last time.

**Comment by srcnalt** [comment]
:cough: ᵃᵇᵒᵘᵗ ᵗʰᵉ ᵇᵒᵘᶰᵗʸ :cough: :smile:

**Pull request merged**
